<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'Netresearch\\RteCKEditorImage\\' => array($typo3InstallDir . 'typo3conf/ext/rte_ckeditor_image/Classes'),
);
