<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nctemplate"
 *
 * Auto generated by Extension Builder 2015-11-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NETCASE GmbH TYPO3 Template',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Roman Stulz',
	'author_email' => 'roman.stulz@netcase.ch',
	'state' => 'stable',
	'internal' => '0.0.1',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
